Merged Doug's pgpool/postgres HA changes

diff --git a/sas-software-deployment/templates/static-roles/sasdatasvrc/files/sasdatasvrc_datanodes b/sas-software-deployment/templates/static-roles/sasdatasvrc/files/sasdatasvrc_datanodes
--- a/sas-software-deployment/templates/static-roles/sasdatasvrc/files/sasdatasvrc_datanodes
+++ b/sas-software-deployment/templates/static-roles/sasdatasvrc/files/sasdatasvrc_datanodes
@@ -50,11 +50,14 @@ function primary_data_node() {
 function secondary_data_node() {
     primary_ip=$1
     primary_uid=$2
+    perform_restart=${3:-false}
 
-    if [ ! -e "${HOME}/.pgpass" ]; then
-        touch ${HOME}/.pgpass
-        chmod 0600 ${HOME}/.pgpass
-        echo >>${HOME}/.pgpass "*:*:*:${SASPOSTGRESREPLUSER}:${SASPOSTGRESREPLPWD}"
+    pg_user_home_dir=$(getent passwd ${SASPOSTGRESOWNER}|awk -F: '{print $6}')
+    if [ ! -e ${pg_user_home_dir}/.pgpass ]; then
+        touch ${pg_user_home_dir}/.pgpass
+        chmod 0600 ${pg_user_home_dir}/.pgpass
+        chown ${SASPOSTGRESOWNER} ${pg_user_home_dir}/.pgpass
+        echo >> ${pg_user_home_dir}/.pgpass "*:*:*:${SASPOSTGRESREPLUSER}:${SASPOSTGRESREPLPWD}"
     fi
 
     if [ -z "${primary_ip}" ]; then
@@ -62,16 +65,16 @@ function secondary_data_node() {
         exit 1
     fi
 
-    if [ -d ${PG_DATADIR} ]; then
-        echo_line "INFO: removing data directory..."
-        success=false
-        rm -rf ${PG_DATADIR}
+    # if [ -d ${PG_DATADIR} ]; then
+    #     echo_line "INFO: removing data directory..."
+    #     success=false
+    #     rm -rf ${PG_DATADIR} && success=true
 
-        if ! $success; then
-            echo_line "ERROR: Deleting data directory failed."
-            exit 5
-        fi
-    fi
+    #     if ! $success; then
+    #         echo_line "ERROR: Deleting data directory failed."
+    #         exit 5
+    #     fi
+    # fi
 
     if [ ! -d ${PG_DATADIR} ]; then
         echo_line "INFO: Initializing backup..."
@@ -109,6 +112,9 @@ EOL
     chown ${SASPOSTGRESOWNER}:${SASPOSTGRESGROUP} ${PG_DATADIR}/recovery.conf
     chmod 0644 ${PG_DATADIR}/recovery.conf
 
+    if ${perform_restart}; then
+        su - -c "${SASHOME}/bin/pg_ctl -o '-c config_file=${SASPOSTGRESCONFIGDIR}/postgresql.conf -c hba_file=${SASPOSTGRESCONFIGDIR}/pg_hba.conf' -D ${PG_DATADIR} -w -t 30 restart" ${SASPOSTGRESOWNER}
+    fi
     echo_line "INFO: Recording primary ip in Consul at config/${SASSERVICENAME}/sas.dataserver.pool/backend/${SASINSTANCE}/primary"
     ${BOOTSTRAP_CONFIG} kv write --force config/${SASSERVICENAME}/sas.dataserver.pool/backend/${SASINSTANCE}/primary ${primary_ip}
     ${BOOTSTRAP_CONFIG} kv write --force config/${SASSERVICENAME}/sas.dataserver.pool/backend/${SASINSTANCE}/primary_uid ${primary_uid}
