Removed inner level readme from multicontainer

diff --git a/addons/ide-jupyter-python3/Dockerfile_http b/addons/ide-jupyter-python3/Dockerfile_http
--- a/addons/ide-jupyter-python3/Dockerfile_http
+++ b/addons/ide-jupyter-python3/Dockerfile_http
@@ -28,16 +28,25 @@ ARG BASETAG=latest
 FROM $BASEIMAGE:$BASETAG
 
 ARG PLATFORM=redhat
+ARG PROJECT_NAME=sas-viya
 
 USER root
 COPY proxy.conf ./jpy3_proxy.conf
 
 RUN set -e; \
-    if [ "$PLATFORM" = "redhat" ]; then \
-        cp ./jpy3_proxy.conf /etc/httpd/conf.d/jpy3_proxy.conf; \
-    elif [ "$PLATFORM" = "suse" ]; then \
-        cp ./jpy3_proxy.conf /etc/apache2/conf.d/jpy3_proxy.conf; \
-    else \
-        echo; echo "####### [ERROR] : Unknown platform of \"$PLATFORM\" passed in"; echo; \
-        exit 1; \
+     if [ "$PLATFORM" = "redhat" ]; then \
+        if [ "$BASEIMAGE" != "viya-single-container" ]; then \
+            sed "s/localhost/$PROJECT_NAME-programming/g" ./jpy3_proxy.conf > /etc/httpd/conf.d/jpy3_proxy.conf; \
+        else \
+            cp ./jpy3_proxy.conf /etc/httpd/conf.d/jpy3_proxy.conf; \
+        fi; \
+     elif [ "$PLATFORM" = "suse" ]; then \
+        if [ "$BASEIMAGE" != "viya-single-container" ]; then \
+            sed "s/localhost/$PROJECT_NAME-programming/g" ./jpy3_proxy.conf > /etc/apache2/conf.d/jpy3_proxy.conf; \
+        else \
+            cp ./jpy3_proxy.conf /etc/apache2/conf.d/jpy3_proxy.conf; \
+        fi; \
+     else \
+         echo; echo "####### [ERROR] : Unknown platform of \"$PLATFORM\" passed in"; echo; \
+         exit 1; \
     fi;
